spring.application.name=MovieScope
server.port=8080
tmdb.api.key=66ba0b8e9dff36277dda546985e03c18
tmdb.api.base-url=https://api.themoviedb.org/3
spring.datasource.url=jdbc:mysql://localhost:3306/MoviesDetails
spring.datasource.password=Qwerty@123
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
